### ISSUE TITLE
Resolved Questions

### ISSUE THREAD

**Issue by WYW0** [xioTechnologies/Gait-Tracking#11]
Hello！Can you tell me where the "import imufusion" in your code comes from?

**Comment by xioTechnologies** [comment]
"_problem_" is not an appropriate title for an issue.  Please retitle this issue so that it will be useful to others.

[imufusion](https://pypi.org/project/imufusion/) is a Python package and is distributed on PyPI.  It is installed the same way as any other Python package, using `pip install`.

**Comment by WYW0** [comment]
Okay, I've found it, thank you
