### ISSUE TITLE
Gait Tracking with custom data

### ISSUE THREAD

**Issue by psdii** [xioTechnologies/Gait-Tracking#13]
I want to use my own data from my own IMU. I was wondering how important is it that the timestamps on the 2 sets of sensors match?
Does the code expect an exact sample rate or an average sample rate? (my sensor is able to get an average of 50 hz, but its not perfectly logging every 0.002 seconds)

**Comment by xioTechnologies** [comment]
I suggest that the best way to evaluate the performance of your system is for you to test it.  No real-world system provides "perfect" measurements.

**Comment by psdii** [comment]
Would that mean that the gait python program requires the data to be at 50 hz for the entirety of the dataset?
