### ISSUE TITLE
Module 'imufusion' has no attribute 'CONVENTION_NWU'

### ISSUE THREAD

**Issue by Alx2203** [xioTechnologies/Gait-Tracking#14]
Hello, thank you very much for your project which helps me a lot. However I wanted to test your code and I get this error:

AttributeError: module 'imufusion' has no attribute 'CONVENTION_NWU'

I'm sorry if this is a silly question but I'm a beginner. I checked that the latest version of imufusion was installed. I'm working on conda, maybe that's where the problem comes from?

Thanks in advance for your help.

**Comment by xioTechnologies** [comment]
I expect you are not using the latest version of [imufusion](https://www.piwheels.org/project/imufusion/).  I am not familiar with conda so I am not able to suggest a solution.  I suggest you search online.  There many Python guides and tutorials for beginners.

**Comment by Alx2203** [comment]
Ok I solved my first problem. Now I have a second one x)
I tested the code with your short_walk and long_walk data and it worked perfectly. When I test with my IMU I consistently get an increase along the z axis while my data was obtained flat.
![1](https://user-images.githubusercontent.com/132068185/235309832-d34e6684-1875-474b-a0aa-855dc720d4a0.png)
![2](https://user-images.githubusercontent.com/132068185/235309835-d7ccdb0b-bef5-483a-8380-2a7941f7426b.png)


Other than a calibration problem, do you have any idea where the problem is coming from?

**Comment by xioTechnologies** [comment]
Other users have asked similar questions.  Please read through the closed issues for this repository.

**Comment by Alx2203** [comment]
Sorry I didn't pay attention to the closed issues.
Ok it also seems that my problem was also due to the IMU being too loose yet I was already attaching the IMU to the laces.
By the way, where exactly do you place the IMU at the laces (rather close to the toes or the ankle)? Do you have any tips on how to make sure the IMU is tightly attached?

**Comment by xioTechnologies** [comment]
Above the toes or on the laces of a shoe are often convenient locations.  I suggest using an elasticated strap or if the show is big enough then tucking the IMU between the tongue and the laces.
