### ISSUE TITLE
`acceleration_rejection_timer` is removed? 

### ISSUE THREAD

**Issue by jiefengsun** [xioTechnologies/Gait-Tracking#15]
Hello, 
Very nice demo
But when I run it, `ahrs_internal_states.acceleration_rejection_timer`, gives me an error. 

Should I replace it with ` ahrs_internal_states.acceleration_recovery_trigger`

**Comment by xioTechnologies** [comment]
[gait_tracking.py](https://github.com/xioTechnologies/Gait-Tracking/blob/main/gait_tracking.py) works with the latest release of [imufusion](https://github.com/xioTechnologies/Fusion), [v1.1.2](https://pypi.org/project/imufusion/).  Please use this version to avoid errors.
