### ISSUE TITLE
Error: 0.082 m

### ISSUE THREAD

**Issue by Rocky-YU** [xioTechnologies/Gait-Tracking#18]
Hello,
Thanks for sharing your code, I am getting some errors while running your code. For the parameters and data of the code I did not make any changes. But still this error occurs.
"
D:\ProgramData\Anaconda3\envs\labelme\python.exe D:/code/Gait-Tracking/gait_tracking.py
Error: 0.082 m
"
What should I do about it, please?
Thank you.

**Comment by xioTechnologies** [comment]
That is not a runtime error.  It is a printed message indicating the calculated error in the final position in meters.

**Comment by Rocky-YU** [comment]
I see, thank you.

**Comment by Rocky-YU** [comment]
> That is not a runtime error. It is a printed message indicating the calculated error in the final position in meters.

I see, thank you.
