### ISSUE TITLE
a drop in Z-axis

### ISSUE THREAD

**Issue by zhang1796183796** [xioTechnologies/Gait-Tracking#21]
hi,i have met a problem ，When I tested using my own data, there was a deviation of g in the acceleration of the z-axis. How should I eliminate it。
![ceaaa8de647aae203b59430321ec43b](https://github.com/xioTechnologies/Gait-Tracking/assets/52670557/7449d90c-48e6-4873-aead-ce0560ecde70)

**Comment by zhang1796183796** [comment]
![Uploading ceaaa8de647aae203b59430321ec43b.png…]()

**Comment by zhang1796183796** [comment]
![ceaaa8de647aae203b59430321ec43b](https://github.com/xioTechnologies/Gait-Tracking/assets/52670557/64c739d3-d293-4d86-91d2-54a7bd52a819)

**Comment by xioTechnologies** [comment]
The issue is specific to your system but it is not possible to comment further without more information.  The code works with the example data provided.  The example data was collected using an [NGIMU](https://x-io.co.uk/ngimu/).

**Comment by zhang1796183796** [comment]
> The issue is specific to your system but it is not possible to comment further without more information. The code works with the example data provided. The example data was collected using an [NGIMU](https://x-io.co.uk/ngimu/).

i just walk on the plane.but there is acceleration  drop aruond g on z axis.,in figure one .

**Comment by xioTechnologies** [comment]
The accelerations look very high.  Perhaps you are providing measurements in m/s/s when g is expected.
