### ISSUE TITLE
Calclu linear displacement

### ISSUE THREAD

**Issue by Sinou12** [xioTechnologies/Gait-Tracking#6]
Hello, 

First I would like to thank you for the experiment you did and the information so rewarding. 

I am a civil engineering student and I want to use the IMU sensor to determine the displacement of a particle. 

I am currently using a WitMotion Bluetooth BLE 5.0 9 Axis WT901BLE sensor. 

For the calibration of the sensor, I use the software provided by the company Witmotion. 

The recording is done by a frequency of 20 Hz. I try to have first simple displacements, like 30 or 50 cm on the X axis. 

I entered my data in your code by changing the frequency, but I still get zero speed and zero displacement. 

Can you tell me if this code can work in my case, if so what are the parameters to change? 
If not, can you direct me to other codes, or what do you recommend? 

Thank you

**Comment by xioTechnologies** [comment]
The code is for tracking an IMU attached to a foot during walking.  It cannot be easily repurposed for other types of motion.  I am not able to recommend anything I think would be useful to you.
