### ISSUE TITLE
Acceleration computation

### ISSUE THREAD

**Issue by ricber** [xioTechnologies/Gait-Tracking#7]
Hi, can you exaplain why you multiply the earth acceleration by the gravitational acceleration (9.81)?

https://github.com/xioTechnologies/Gait-Tracking/blob/ccc5521946634d3f4c69ba5b237f6e28f0f89359/gait_tracking.py#L64

**Comment by xioTechnologies** [comment]
To convert from [g](https://en.wikipedia.org/wiki/Gravity_of_Earth) to m/s/s, as stated in the comment.

**Comment by ricber** [comment]
Yes, of course, I read the comment. But what does it mean to convert g to m/s/s? g is already in m/s/s and what does it mean to multiply g by the earth acceleration you computed?

**Comment by zhang1796183796** [comment]
hi,how the gyroscope in used in acceleration computation?
